version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    working_dir: /app
    command: sh -c "npm install && npm run build"
    volumes:
      - ./frontend:/app
    # Ждать сборки фронта не нужно, nginx поднимется параллельно

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env # если есть .env
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run start:prod"

  nginx:
    image: nginx:1.24
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
