version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    expose:
      - "5000"

  nginx:
    image: nginx:1.24
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
