version: '3.8'
services:
  frontend:
    image: nginx:1.24
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend
    expose:
      - "5000"
    restart: unless-stopped
