# Стадия сборки
FROM node:18 AS builder

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json* ./
RUN npm install

COPY frontend/ ./

RUN npm run build

# Стадия продакшн
FROM nginx:alpine

# Копируем собранный build в директорию Nginx
COPY --from=builder /app/build /usr/share/nginx/html

# Кастомный конфиг (по желанию, иначе будет дефолтный)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
